version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      MONGO_URI: "mongodb://mongo:27017/db"
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

