name: Deploy to AWS EKS

on:
  push:
    branches:
      - main https://github.com/akylgit/devops-final.git #Trigger deploy on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push frontend Docker image to Docker Hub
      - name: Build and Push Frontend Docker image
        working-directory: ./frontend # Adjust path if needed
        run: |
          docker build -t akyldocker25/final-frontend:latest .
          docker push akyldocker25/final-frontend:latest

      # Build and push backend Docker image to Docker Hub
      - name: Build and Push Backend Docker image
        working-directory: ./backend # Adjust path if needed
        run: |
          docker build -t akyldocker25/final-backend:latest .
          docker push akyldocker25/final-backend:latest

      # Set up AWS credentials to interact with EKS
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Configure kubectl to interact with EKS
      - name: Configure kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name my-eks-cluster

      # Deploy to AWS EKS from deployment.yaml
      - name: Deploy to EKS
        run: |
          kubectl apply -f frontend-deployment.yaml  # Use your actual path for the deployment.yaml file
          kubectl apply -f backend-deployment.yaml     # Optional: service.yaml for exposing the app

      - name: Verify the deployment
        run: |
          kubectl get pods
          kubectl get svc
